const C=window.STORE_CONFIG;
const $=id=>document.getElementById(id);
const isTop=String(C.brandName||'').toLowerCase().includes('top watch');
const languageKey=`watchStoreLanguage:${C.brandName||'store'}`;
let saved='';try{saved=localStorage.getItem(languageKey)||''}catch(e){}
const state={products:[],filtered:[],selectedBrands:new Set(),language:saved==='en'?'en':'fil',lastLoadedAt:0,activeProduct:null,choice:{size:'',grade:''}};

const COPY={
 fil:{search:'Hanapin',fast:'MABILISANG PILI',topTitle:'Pinakamabentang Relo',topDescription:'Top 6 na relo batay sa naitalang benta.',catalog:'CATALOG',available:'Mga Available na Relo',catalogPlaceholder:'I-type ang brand, model, style, o reference',allBrands:'Lahat ng Brand',brandsSelected:n=>`${n} brand ang napili`,empty:'Walang nakitang relo. Subukan ang ibang brand o search term.',special:'ESPESYAL NA REQUEST',requestTitle:'Hindi mo makita ang gusto mong relo?',requestDescription:'Sabihin sa amin ang gusto mong relo at tutulungan ka naming hanapin ito.',requestButton:'Mag-request ng Relo',details:'Detalye',orderNow:'Umorder Ngayon',choose:'Pumili muna ng variant',size:'Sukat',grade:'Grade',brand:'Brand',reference:'Reference',price:'Presyo',product:'Produkto',loaded:n=>`${n} available na relo · live inventory`,unavailable:'Hindi ma-load ang live inventory',newArrival:'Bagong dating',sales:n=>`${n} naitalang benta`,contact:'Contact info',messageUs:'I-message Kami',from:'Mula',entry:'Entry tier',mid:'Mid tier',top:'Top tier',selectSize:'Piliin ang sukat',selectGrade:'Piliin ang grade'},
 en:{search:'Search',fast:'FAST PICKS',topTitle:'Top-Selling Watches',topDescription:'Top 6 watches based on recorded sales.',catalog:'LIVE CATALOG',available:'Available Watches',catalogPlaceholder:'Type brand, model, style, or reference',allBrands:'All brands',brandsSelected:n=>`${n} brands selected`,empty:'No watch found. Try another brand or search term.',special:'SPECIAL REQUEST',requestTitle:"Don't see the watch you like?",requestDescription:'Tell us your desired watch and we’ll help you look for it.',requestButton:'Request a Watch',details:'Details',orderNow:'Order Now',choose:'Select a variant first',size:'Size',grade:'Grade',brand:'Brand',reference:'Reference',price:'Price',product:'Product',loaded:n=>`${n} available watch${n===1?'':'es'} · live inventory`,unavailable:'Live inventory unavailable',newArrival:'New arrival',sales:n=>`${n} recorded sale${n===1?'':'s'}`,contact:'Contact info',messageUs:'Message Us',from:'From',entry:'Entry tier',mid:'Mid tier',top:'Top tier',selectSize:'Select size',selectGrade:'Select grade'}
};
const BRAND={
 top:{fil:{heroTitle:'Relo para sa modernong lalaki.',heroDescription:'Hanapin ayon sa model, brand, o reference. Tingnan ang detalye at umorder direkta sa amin.',heroPlaceholder:'Hanapin ang relo, brand, o reference',footer:'Quality watches. Tapat na presyo. Simpleng order.'},en:{heroTitle:'Built for the modern man.',heroDescription:'Search by model, brand, or reference. Review the details and order directly.',heroPlaceholder:'Search watch, brand, or reference',footer:'Quality watches. Honest pricing. Simple ordering.'}},
 master:{fil:{heroTitle:'Sulit na relo. Simpleng pag-order.',heroDescription:'Hanapin ang eksaktong relo, tingnan ang live availability, at umorder direkta.',heroPlaceholder:'Hanapin ang relo, brand, o reference',footer:'Sulit na relo. Live inventory. Simpleng order.'},en:{heroTitle:'Good finds. Simple ordering.',heroDescription:'Search the exact watch you want, check live availability, then order directly.',heroPlaceholder:'Search watch, brand, or reference',footer:'Good-value watches. Live inventory. Simple ordering.'}}
};
const t=k=>COPY[state.language][k], bt=k=>BRAND[isTop?'top':'master'][state.language][k];
const text=(id,v)=>{const e=$(id);if(e)e.textContent=v}, placeholder=(id,v)=>{const e=$(id);if(e)e.placeholder=v};

setupEvents();setupContacts();applyLanguage();loadProducts();
const refreshMs=Math.max(30000,Number(C.refreshIntervalMs||60000));
setInterval(()=>{if(!document.hidden)loadProducts({silent:true})},refreshMs);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-state.lastLoadedAt>15000)loadProducts({silent:true})});

function setupEvents(){
 $('closeDialog')?.addEventListener('click',()=>$('productDialog').close());
 $('heroSearchButton')?.addEventListener('click',()=>{if($('catalogSearch'))$('catalogSearch').value=$('heroSearch')?.value||'';runSearch();document.querySelector('.catalog-shell')?.scrollIntoView({behavior:'smooth'})});
 $('heroSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('heroSearchButton')?.click()});
 $('catalogSearch')?.addEventListener('input',runSearch);
 $('brandFilterButton')?.addEventListener('click',e=>{e.stopPropagation();$('brandFilterMenu')?.classList.toggle('hidden')});
 $('brandFilterMenu')?.addEventListener('click',e=>e.stopPropagation());
 $('topPrev')?.addEventListener('click',()=>scrollTop(-1));$('topNext')?.addEventListener('click',()=>scrollTop(1));
 $('filButton')?.addEventListener('click',()=>setLanguage('fil'));$('engButton')?.addEventListener('click',()=>setLanguage('en'));
 document.addEventListener('click',()=>$('brandFilterMenu')?.classList.add('hidden'));
}
function setLanguage(l){state.language=l==='en'?'en':'fil';try{localStorage.setItem(languageKey,state.language)}catch(e){}applyLanguage();updateBrandFilterButton();renderTop();renderProducts(state.filtered);if(state.activeProduct&&$('productDialog')?.open)openProfile(state.activeProduct)}
function applyLanguage(){
 document.documentElement.lang=state.language==='fil'?'fil':'en';$('filButton')?.classList.toggle('active',state.language==='fil');$('engButton')?.classList.toggle('active',state.language==='en');
 text('heroTitle',bt('heroTitle'));text('heroDescription',bt('heroDescription'));placeholder('heroSearch',bt('heroPlaceholder'));text('heroSearchButton',t('search'));
 text('fastPicksLabel',t('fast'));text('topSellingTitle',t('topTitle'));text('topSellingDescription',t('topDescription'));text('catalogLabel',t('catalog'));text('availableTitle',t('available'));placeholder('catalogSearch',t('catalogPlaceholder'));text('emptyMessage',t('empty'));
 text('checkoutLabel',t('special'));text('quickOrderTitle',t('requestTitle'));text('quickOrderDescription',t('requestDescription'));text('requestWatchLink',t('requestButton'));text('footerTagline',bt('footer'));text('contactTitle',t('contact'));text('contactToggleText',t('messageUs'));updateStatus();
}
async function loadProducts({silent=false}={}){
 try{
  const sep=C.apiUrl.includes('?')?'&':'?';const r=await fetch(`${C.apiUrl}${sep}store=${encodeURIComponent(C.storeFilter||'all')}&_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);
  const d=await r.json();if(!d.success||!Array.isArray(d.products))throw new Error(d.error||'Bad inventory');
  state.products=d.products.filter(p=>Number(p.stock||0)>0&&p.visible!==false).sort(sortSales);state.lastLoadedAt=Date.now();fillBrands();renderTop();runSearch();updateStatus();applyLuxuryBackground();
 }catch(e){console.error(e);if(!silent){state.products=[];state.filtered=[];renderTop();renderProducts([]);updateStatus(true)}}
}
const sortSales=(a,b)=>Number(b.sold||0)-Number(a.sold||0)||String(a.name||'').localeCompare(String(b.name||''));
function updateStatus(err=false){if(!$('inventoryStatus'))return;text('inventoryStatus',err?t('unavailable'):t('loaded')(state.products.length))}
function fillBrands(){const m=$('brandFilterMenu');if(!m)return;const brands=[...new Set(state.products.map(p=>String(p.category||p.brand||'').trim()).filter(Boolean))].sort();const valid=new Set(brands.map(x=>x.toLowerCase()));state.selectedBrands=new Set([...state.selectedBrands].filter(x=>valid.has(x)));m.innerHTML='';brands.forEach(brand=>{const key=brand.toLowerCase(),lab=document.createElement('label'),inp=document.createElement('input'),sp=document.createElement('span');lab.className='brand-option';inp.type='checkbox';inp.checked=state.selectedBrands.has(key);inp.onchange=()=>{inp.checked?state.selectedBrands.add(key):state.selectedBrands.delete(key);updateBrandFilterButton();runSearch()};sp.textContent=brand;lab.append(inp,sp);m.appendChild(lab)});updateBrandFilterButton()}
function updateBrandFilterButton(){const b=$('brandFilterButton');if(!b)return;const n=state.selectedBrands.size;if(!n){b.textContent=`${t('allBrands')} ▾`;return}if(n===1){const k=[...state.selectedBrands][0],p=state.products.find(x=>String(x.category||x.brand||'').toLowerCase()===k);b.textContent=`${p?.category||p?.brand||k} ▾`;return}b.textContent=`${t('brandsSelected')(n)} ▾`}
function runSearch(){const q=($('catalogSearch')?.value||'').trim().toLowerCase();state.filtered=state.products.filter(p=>{const brand=String(p.category||p.brand||'').toLowerCase(),s=[p.sku,p.name,p.category,p.brand,p.grade,p.reference,...Object.values(p.specs||{})].join(' ').toLowerCase();return(!state.selectedBrands.size||state.selectedBrands.has(brand))&&(!q||s.includes(q))}).sort(sortSales);renderProducts(state.filtered)}
function renderTop(){const c=$('topSellers');if(!c)return;c.innerHTML='';state.products.slice(0,6).forEach(p=>c.appendChild(card(p)))}
function scrollTop(dir){const c=$('topSellers');if(c)c.scrollBy({left:dir*c.clientWidth,behavior:'smooth'})}
function renderProducts(list){const g=$('productGrid');if(!g)return;g.innerHTML='';$('emptyState')?.classList.toggle('hidden',list.length>0);list.forEach(p=>g.appendChild(card(p)))}

function parseSizes(p){return uniq(String(p.specs?.['Available Sizes']||p.size||'').split(/[,/|]+/).map(x=>x.trim()).filter(Boolean))}
function parseGrades(p){if(Array.isArray(p.variants)&&p.variants.length)return uniq(p.variants.filter(v=>Number(v.stock||0)>0&&v.active!==false).map(v=>cleanGrade(v.grade)).filter(Boolean));const out=[];['Japan','Swiss','Super C'].forEach(g=>{if(String(p.specs?.[g]||'').trim())out.push(g)});return uniq(out)}
function normalVariants(p){if(Array.isArray(p.variants)&&p.variants.length)return p.variants.filter(v=>Number(v.stock||0)>0&&v.active!==false).map(v=>({sku:v.sku||v.variantSku||'',size:String(v.size||'').trim(),grade:cleanGrade(v.grade),price:Number(v.price??v.sellingPrice??p.price??0),stock:Number(v.stock||0)}));const sizes=parseSizes(p),grades=parseGrades(p),ss=sizes.length?sizes:[''],gg=grades.length?grades:[''],out=[];ss.forEach(size=>gg.forEach(grade=>out.push({sku:'',size,grade,price:Number(gradePriceFromProduct(p,grade)??p.price??0),stock:Number(p.stock||0)})));return out}
function gradePriceFromProduct(p,grade){const k=cleanGrade(grade),gp=p.gradePrices||{};return gp[k]??gp[k.toLowerCase()]??p[`${k.replace(/\s+/g,'')}Price`]??null}
function cleanGrade(g){const x=String(g||'').replace(/\s*\([^)]*\)\s*/g,'').trim();return /^super\s*c/i.test(x)?'Super C':/^swiss/i.test(x)?'Swiss':/^japan/i.test(x)?'Japan':x}
function uniq(a){return [...new Set(a)]}
function gradeMeta(g){const k=cleanGrade(g);if(k==='Japan')return{symbol:'◆',label:t('entry'),className:'tier-japan'};if(k==='Swiss')return{symbol:'◆◆',label:t('mid'),className:'tier-swiss'};return{symbol:'◆◆◆',label:t('top'),className:'tier-super'}}
function productPrice(p){const prices=normalVariants(p).map(v=>v.price).filter(x=>x>0);return prices.length?Math.min(...prices):Number(p.price||0)}
function priceLabel(p){const prices=uniq(normalVariants(p).map(v=>Number(v.price||0)).filter(Boolean)),min=prices.length?Math.min(...prices):Number(p.price||0);return prices.length>1?`${t('from')} ${money(min)}`:money(min)}
function requiresChoice(p){const v=normalVariants(p);return uniq(v.map(x=>x.size).filter(Boolean)).length>1||uniq(v.map(x=>x.grade).filter(Boolean)).length>1}

function card(p){
 const a=document.createElement('article');a.className='product-card';const image=p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:'⌚';const sales=Number(p.sold||0)>0?t('sales')(Number(p.sold||0)):t('newArrival');
 a.innerHTML=`<div class="product-photo">${image}</div><div class="product-body"><div class="product-meta"><span>${esc(p.category||p.brand||'Watch')}</span><span>${esc(p.sku||'')}</span></div><h3 class="product-name">${esc(p.name||'Unnamed Watch')}</h3><div class="product-price">${esc(priceLabel(p))}</div><span class="stock-badge available">Available · ${Number(p.stock||0)} left</span><div class="sold-count">${esc(sales)}</div>${requiresChoice(p)?`<div class="variant-hint">${esc(t('choose'))}</div>`:''}<div class="card-actions"><button class="details-button" type="button">${esc(t('details'))}</button><button class="order-now" type="button">${esc(t('orderNow'))}</button></div></div>`;
 a.querySelector('.details-button').onclick=()=>openProfile(p);a.querySelector('.order-now').onclick=()=>requiresChoice(p)?openProfile(p,true):quickOrder(p);return a;
}
function quickOrder(p){const v=normalVariants(p)[0]||{size:'',grade:'',price:productPrice(p),sku:''};sendOrder(p,v)}
function openProfile(p,focus=false){
 state.activeProduct=p;state.choice={size:'',grade:''};const vars=normalVariants(p),sizes=uniq(vars.map(v=>v.size).filter(Boolean)),grades=uniq(vars.map(v=>v.grade).filter(Boolean));if(sizes.length===1)state.choice.size=sizes[0];if(grades.length===1)state.choice.grade=grades[0];
 const sizeUI=sizes.length?`<div class="variant-section"><div class="variant-label">${esc(t('selectSize'))}</div><div id="sizeTiles" class="size-tiles">${sizes.map(s=>`<button type="button" class="size-tile${state.choice.size===s?' selected':''}" data-size="${esc(s)}">${esc(s)}</button>`).join('')}</div></div>`:'';
 const gradeUI=grades.length?`<div class="variant-section"><div class="variant-label">${esc(t('selectGrade'))}</div><div id="gradeTiles" class="grade-tiles">${grades.map(g=>gradeTile(g,p,vars)).join('')}</div></div>`:'';
 const specs=Object.entries(p.specs||{}).filter(([k])=>!['Available Sizes','Japan','Swiss','Super C'].includes(k)).map(([k,v])=>`<div class="spec-row"><span>${esc(k)}</span><span>${esc(v)}</span></div>`).join('');
 $('dialogBody').innerHTML=`<div class="product-profile"><div class="profile-image">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'⌚'}</div><div class="profile-info"><div class="profile-sku">${esc(p.sku||'')}</div><h2>${esc(p.name||'Unnamed Watch')}</h2><div id="profilePrice" class="profile-price">${esc(priceLabel(p))}</div><span class="stock-badge available">Available · ${Number(p.stock||0)} left</span><p class="profile-description">${esc(p.description||'')}</p><div class="variant-picker">${sizeUI}${gradeUI}</div><div class="specs"><div class="spec-row"><span>${esc(t('brand'))}</span><span>${esc(p.category||p.brand||'Watch')}</span></div>${specs}</div><button id="profileOrderNow" class="primary-action profile-order-button" type="button">${esc(t('orderNow'))}</button><div id="variantWarning" class="variant-warning hidden">${esc(t('choose'))}</div></div></div>`;
 wireVariantButtons(p,vars,sizes,grades);if(!$('productDialog').open)$('productDialog').showModal();if(focus)setTimeout(()=>document.querySelector('.variant-picker')?.scrollIntoView({block:'center',behavior:'smooth'}),80);
}
function gradeTile(g,p,vars){const m=gradeMeta(g),prices=uniq(vars.filter(v=>v.grade===g).map(v=>v.price).filter(Boolean)),price=prices.length?Math.min(...prices):gradePriceFromProduct(p,g)||p.price||0;return `<button type="button" class="grade-tile ${m.className}${state.choice.grade===g?' selected':''}" data-grade="${esc(g)}"><span class="grade-symbol">${m.symbol}</span><span class="grade-copy"><strong>${esc(g==='Super C'?'Super C (1:1)':g)}</strong><small>${esc(m.label)}</small></span><span class="grade-price">${money(price)}</span></button>`}
function wireVariantButtons(p,vars,sizes,grades){
 const sizeBtns=[...document.querySelectorAll('.size-tile')],gradeBtns=[...document.querySelectorAll('.grade-tile')],order=$('profileOrderNow');const compatible=()=>vars.filter(v=>(!state.choice.size||v.size===state.choice.size)&&(!state.choice.grade||v.grade===state.choice.grade));
 function refresh(){sizeBtns.forEach(b=>{const s=b.dataset.size,ok=vars.some(v=>v.size===s&&(!state.choice.grade||v.grade===state.choice.grade));b.disabled=!ok;b.classList.toggle('selected',state.choice.size===s)});gradeBtns.forEach(b=>{const g=b.dataset.grade,ok=vars.some(v=>v.grade===g&&(!state.choice.size||v.size===state.choice.size));b.disabled=!ok;b.classList.toggle('selected',state.choice.grade===g)});const needS=sizes.length>1,needG=grades.length>1,ready=(!needS||!!state.choice.size)&&(!needG||!!state.choice.grade)&&compatible().length>0;order.disabled=!ready;$('variantWarning')?.classList.toggle('hidden',ready);const options=compatible(),prices=uniq(options.map(v=>v.price).filter(Boolean));if($('profilePrice'))$('profilePrice').textContent=prices.length===1?money(prices[0]):prices.length>1?`${t('from')} ${money(Math.min(...prices))}`:priceLabel(p)}
 sizeBtns.forEach(b=>b.onclick=()=>{state.choice.size=b.dataset.size;refresh()});gradeBtns.forEach(b=>b.onclick=()=>{state.choice.grade=b.dataset.grade;refresh()});refresh();order.onclick=()=>{const exact=compatible();if(order.disabled||!exact.length)return;sendOrder(p,exact.sort((a,b)=>a.price-b.price)[0])};
}
function sendOrder(p,v){const msg=orderMessage(p,v);try{navigator.clipboard?.writeText(msg)}catch(e){}window.open(messenger(msg),'_blank','noopener')}
function orderMessage(p,v){const s=p.specs||{};return [t('orderNow'),`${t('product')}: ${p.name||''}`,`${t('brand')}: ${p.category||p.brand||''}`,`${t('reference')}: ${p.reference||s.Reference||''}`,v.size?`${t('size')}: ${v.size}`:'',v.grade?`${t('grade')}: ${v.grade==='Super C'?'Super C (1:1)':v.grade}`:'',`${t('price')}: ${money(v.price||productPrice(p))}`,v.sku?`SKU: ${v.sku}`:`SKU: ${p.sku||''}`].filter(Boolean).join('\n')}
function messenger(msg){const b=C.messengerUrl||C.facebookUrl||'#',sep=b.includes('?')?'&':'?';return b==='#'?b:`${b}${sep}text=${encodeURIComponent(msg)}`}

function setupContacts(){if($('contactPhone')){$('contactPhone').href=C.phoneUrl||'#';text('contactPhoneText',C.phoneDisplay||'')}if($('contactEmail')){$('contactEmail').href=C.email?`mailto:${C.email}`:'#';text('contactEmailText',C.email||'')}if($('contactWhatsapp')){$('contactWhatsapp').href=C.whatsappUrl||'#';text('contactWhatsappText',C.whatsappDisplay||'')}if($('contactFacebook'))$('contactFacebook').href=C.messengerUrl||C.facebookUrl||'#';$('requestWatchLink')?.addEventListener('click',e=>{e.preventDefault();window.open(messenger(state.language==='fil'?'Hinahanap ko: ':'Looking for: '),'_blank','noopener')});$('contactToggle')?.addEventListener('click',e=>{e.stopPropagation();$('contactPanel')?.classList.toggle('hidden')});$('contactPanel')?.addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',()=>$('contactPanel')?.classList.add('hidden'))}
function applyLuxuryBackground(){const sec=document.querySelector('.quick-order'),img=state.products.find(p=>p.image)?.image;if(sec&&img)sec.style.setProperty('--luxury-watch-bg',`url("${String(img).replace(/"/g,'\\"')}")`)}
const money=v=>new Intl.NumberFormat(C.locale||'en-PH',{style:'currency',currency:C.currency||'PHP',maximumFractionDigits:0}).format(Number(v||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
